import {
  Column,
  CreateDateColumn,
  Entity,
  Index,
  PrimaryGeneratedColumn,
} from 'typeorm';

export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAW = 'WITHDRAW',
  TRANSFER = 'TRANSFER',
  ADJUSTMENT = 'ADJUSTMENT',
  PURCHASE = 'PURCHASE',
}

// Every WITHDRAW/TRANSFER/ADJUSTMENT row is COMPLETED the instant it's
// inserted (the ledger's original guarantee: only successfully applied
// operations are written here, failed attempts go to the Mongo activity log
// instead). DEPOSIT and PURCHASE are the two types that can sit PENDING —
// both now go through the real-money IPG flow: a row is created PENDING,
// the payer is redirected to the IPG, and money only moves once /verify
// confirms the gateway authorized it — and can end as REVERSED if the payer
// never completes/verifies before the timeout, or via an explicit refund
// (PURCHASE only).
export enum TransactionStatus {
  PENDING = 'PENDING',
  COMPLETED = 'COMPLETED',
  REVERSED = 'REVERSED',
}

@Entity('transactions')
export class Transaction {
  @PrimaryGeneratedColumn('uuid')
  id: string;

  @Column({ type: 'enum', enum: TransactionType })
  type: TransactionType;

  @Column({
    type: 'enum',
    enum: TransactionStatus,
    default: TransactionStatus.COMPLETED,
  })
  status: TransactionStatus;

  @Index()
  @Column({ type: 'uuid', nullable: true })
  fromWalletId: string | null;

  @Index()
  @Column({ type: 'uuid', nullable: true })
  toWalletId: string | null;

  @Column({ type: 'bigint' })
  amount: string;

  @Index({ unique: true })
  @Column({ type: 'varchar', length: 255 })
  idempotencyKey: string;

  // Only set for ADJUSTMENT rows: the admin's explanation for the correction.
  @Column({ type: 'varchar', length: 500, nullable: true })
  note: string | null;

  // Only set for ADJUSTMENT rows: which admin performed it.
  @Column({ type: 'uuid', nullable: true })
  performedByUserId: string | null;

  // Only set for PENDING PURCHASE rows: the deadline for the merchant to
  // call /verify before the timeout sweep auto-reverses it.
  @Column({ type: 'timestamptz', nullable: true })
  expiresAt: Date | null;

  // Only set on a REVERSED row's counterpart (or vice versa): links a
  // reversal to the PURCHASE it reverses.
  @Index()
  @Column({ type: 'uuid', nullable: true })
  relatedTransactionId: string | null;

  // Only set for PURCHASE and DEPOSIT rows: the external IPG's payment
  // intent id and the payment page URL the customer was redirected to. No
  // balance moves when these are set — only once /verify confirms the IPG
  // authorized it.
  @Index()
  @Column({ type: 'varchar', length: 100, nullable: true })
  ipgAuthority: string | null;

  @Column({ type: 'varchar', length: 500, nullable: true })
  ipgPaymentUrl: string | null;

  // Only set for PURCHASE rows created via the merchant-initiated charge
  // flow: which language the IPG pay page should render in for the
  // customer identifying themselves there, chosen by the merchant at
  // charge-creation time.
  @Column({ type: 'varchar', length: 5, nullable: true })
  language: string | null;

  // Only set on a COMPLETED PURCHASE credited to a merchant wallet: when its
  // settlement split (see SettlementSplit) was processed by the auto-withdraw
  // sweep, so the sweep never pays the same purchase out twice.
  @Column({ type: 'timestamptz', nullable: true })
  settledAt: Date | null;

  // Only set on a WITHDRAW row generated by a split settlement: which IBAN
  // this particular slice was paid out to.
  @Column({ type: 'varchar', length: 34, nullable: true })
  destinationIban: string | null;

  // Only set on a PURCHASE row created by TransactionsService.payInstallment:
  // which Installment this repayment pays off. verifyPurchase marks that
  // installment PAID and clears the wallet's block once this completes.
  @Index()
  @Column({ type: 'uuid', nullable: true })
  installmentId: string | null;

  @CreateDateColumn({ type: 'timestamptz' })
  createdAt: Date;
}
